<?xml version="1.0"?>
<MessageBundle id="com.cordys.coe.ac.genericldap.Messages">
    <Message id="DELETE_FAILED">
        <MessageText><![CDATA[Delete failed]]></MessageText>
        <Description>
        </Description>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="ERROR_DISCONNECTING_CONNECTION">
        <MessageText><![CDATA[Error disconnecting connection]]></MessageText>
        <Description>
        </Description>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="ERROR_LOST_A_CONNECTION_BECAUSE_IT_COULD_NOT_BE_RECREATED">
        <MessageText><![CDATA[Lost a connection, because it could not be recreated.]]></MessageText>
        <Description>
        </Description>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="ERROR_PREPARING_REQUESTN0">
        <MessageText><![CDATA[Error preparing request:\n{0}]]></MessageText>
        <Description>
        </Description>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="OBJECT_ALREADY_EXISTS">
        <MessageText><![CDATA[Object already exists]]></MessageText>
        <Description>
        </Description>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="connectorManagementDescription">
        <MessageText><![CDATA[This component is used to access an LDAP server.]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="coelibVersionMismatch">
        <MessageText><![CDATA[Coelib version mismatch.]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="connectorStarting">
        <MessageText><![CDATA[Starting GenLDAPConnector Connector.
System Information:
{0}]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="connectorStarted">
        <MessageText><![CDATA[GenLDAPConnector connector started.]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="connectorStartException">
        <MessageText><![CDATA[An error occurred while starting the GenLDAPConnector connector.]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="connectorStopped">
        <MessageText><![CDATA[GenLDAPConnector connector stopped.]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="connectorReset">
        <MessageText><![CDATA[Resetting GenLDAPConnector connector]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="transactionAbort">
        <MessageText><![CDATA[Aborted the transaction.]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="transactionCommit">
        <MessageText><![CDATA[Committed the transaction.]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="transactionError">
        <MessageText><![CDATA[An error occurred while processing the SOAP request: {0}]]></MessageText>
        <Description/>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="CONFIG_SECURITY_PROVIDER_NOT_FOUND">
        <MessageText><![CDATA[Could not find the security provider {0}]]></MessageText>
        <Description>
        </Description>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="UPDATE_ROLLBACK_FAILED_FOR_TUPLE">
        <MessageText><![CDATA[Rollback failed for tuple: {0}]]></MessageText>
        <Description>
        </Description>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="UPDATE_COMMIT_LEVEL_FAILED">
        <MessageText><![CDATA[Commit level failed for {0}]]></MessageText>
        <Description>
        </Description>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
    <Message id="UPDATE_ROLLBACK_FAILED_FOR_DN">
        <MessageText><![CDATA[Rolling back failed for {0}]]></MessageText>
        <Description>
        </Description>
        <Annotations>
            <DocumenationURL/>
        </Annotations>
    </Message>
</MessageBundle>
